baseURL = 'https://gannonlawlor.com/'
languageCode = 'en-us'
title = 'Gannon Lawlor'
theme = ["PaperMod"]

[params]
  [params.assets]
    favicon = "/favicon/favicon.ico"
    favicon16x16 = "/favicon/favicon-16x16.png"
    favicon32x32 = "/favicon/favicon-32x32.png"
    apple_touch_icon = "/favicon/apple-touch-icon.png"
    safari_pinned_tab = "/favicon/favicon.ico"

[menu]
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

